# Generated by Django 5.0.3 on 2024-05-06 08:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nom_medecin', models.CharField(default=None, max_length=100)),
                ('adresse_cabinet', models.CharField(default=None, max_length=255)),
                ('specialite', models.CharField(default=None, max_length=100)),
                ('nom_patient', models.CharField(default=None, max_length=100)),
                ('prenom_patient', models.CharField(default=None, max_length=10)),
                ('num_tel', models.CharField(default=None, max_length=20)),
                ('liste_produits', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pharmacie', models.CharField(max_length=255)),
                ('heure_ouverturep', models.TimeField(blank=True, null=True)),
                ('heure_fermeturep', models.TimeField(blank=True, null=True)),
                ('nom_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pr', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('image', models.CharField(default=None, max_length=2000, null=True)),
                ('type', models.CharField(choices=[('Pharmaceutique', 'Produit Pharmaceutique'), ('Medicament', 'Médicament')], max_length=100)),
                ('Qte', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('ordonnance_requise', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(default=None, max_length=100)),
                ('total', models.CharField(default=None, max_length=200)),
                ('date_commande', models.DateTimeField(auto_now=True)),
                ('ville', models.CharField(max_length=100)),
                ('adr_mail', models.CharField(default=None, max_length=100)),
                ('adresse', models.CharField(default=None, max_length=100)),
                ('num_tel', models.CharField(max_length=15, null=True)),
                ('items', models.CharField(default=None, max_length=300)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='app.pharmacie')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Produit_Prescris',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app.produit')),
                ('id_produitprescris', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prp', models.CharField(max_length=100)),
                ('Descriptionp', models.CharField(max_length=10000, null=True)),
            ],
            bases=('app.produit',),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='produits',
            field=models.ManyToManyField(related_name='pharmacies', to='app.produit'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is_admin')),
                ('is_medecin', models.BooleanField(default=False, verbose_name='Is medecin')),
                ('is_pharmacie', models.BooleanField(default=False, verbose_name='Is pharmacie')),
                ('is_patient', models.BooleanField(default=False, verbose_name='Is patient')),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=255)),
                ('sexe', models.CharField(blank=True, max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medecin', models.CharField(default='Medecin Anonyme', max_length=255)),
                ('adresse_cabinet', models.CharField(blank=True, max_length=255, null=True)),
                ('heure_ouverture', models.TimeField(blank=True, null=True)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('jours_travail', models.CharField(blank=True, max_length=255, null=True)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Admin', models.CharField(default='Admin', max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
