# Generated by Django 5.0.3 on 2024-05-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='infos_patients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
