# Generated by Django 5.0.3 on 2024-05-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medecin_infos_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='infos_patients',
        ),
    ]
