# Generated by Django 5.0.3 on 2024-05-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_medecin_infos_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='age_patient',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='sexe_patient',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
