# Generated by Django 5.0.3 on 2024-05-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ordonnance_age_patient_ordonnance_sexe_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
